# This file describes a conda environment that can be used to install lasp_sdtp
#
# Run the following command to set up this environment:
# $ conda env create -f environment.yml
#
# The environment name can be overridden with the following command:
# $ conda env create -n <custom name> -f environment.yml
#
# Run the following command to activate the environment:
# $ source activate lasp-sdtp
#
# To deactivate the environment run the following command:
# $ source deactivate
#
# To remove the environment entirely, run the following command:
# $ conda env remove -n lasp-sdtp

name: lasp-sdtp

channels:
  - defaults

dependencies:
  - cryptography
  - cx_oracle
  - flask
  - jinja2
  - pandas
  - pip
  - pytest
  - python
  - requests
  - sqlalchemy
  - werkzeug

  - pip:

    # This package
    - -e .