[tool.poetry]
name = "lasp-sdtp"
version = "0.1.0"
description = "Implementation of the NASA Science Data Transfer Protocol (SDTP) Interface for LASP-based applications"
authors = ["Matthew Bourque <matthew.bourque@lasp.colorado.edu>"]
license = "Copyright 2023 Regents of the University of Colorado. All rights reserved."
readme = "README.md"
packages = [{include = "lasp_sdtp"}]

[tool.poetry.dependencies]
python = "^3.9"
cx-Oracle = "^8.3.0"
Flask = "^2.2.2"
Jinja2 = "^3.1.2"
jsonschema = "^4.17.3"
pytest = "^7.2.1"
requests = "^2.28.2"
SQLAlchemy = "^1.4.46"
Werkzeug = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
