[tool.poetry]
name = "lasp-sdtp"
version = "0.1.0"
description = "Implementation of the NASA Science Data Transfer Protocol (SDTP) Interface for LASP-based applications"
authors = ["Matthew Bourque <matthew.bourque@lasp.colorado.edu>"]
license = "Copyright 2024 Regents of the University of Colorado. All rights reserved."
readme = "README.md"
packages = [{include = "lasp_sdtp"}]

[tool.poetry.dependencies]
python = "^3.8"
cx-Oracle = "^8.3.0"
Flask = "2.2.3"
gunicorn = "^20.1.0"
Jinja2 = "^3.1.2"
jsonschema = "^4.17.3"
pandas = "^2.0.0"
pytest = "^7.3.0"
requests = "^2.28.2"
SQLAlchemy = "^2.0.9"
Werkzeug = "^2.2.3"
urllib3 = "1.26.6"

[tool.poetry.group.dev.dependencies]
flake8 = "^5.0.0"
ipython = "^8.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
