[metadata]
name = lasp_sdtp
author = Matthew Bourque
author_email = Matthew.Bourque@lasp.colorado.edu
license = Copyright 2022 Regents of the University of Colorado. All rights reserved.
license_file = LICENSE.txt
url = https://bitbucket.lasp.colorado.edu/projects/SDS/repos/lasp_sdtp/browse
description = Implementation of the NASA Standard Data Transfer Protocol (SDTP) Interface for LASP-based applications
long_description = file: README.md
long_description_content_type = text/markdown
keywords = space, science
classifiers =
    Intended Audience :: Science/Research
    Natural Language :: English
    Topic :: Scientific/Engineering
    Topic :: Scientific/Engineering :: Astronomy
    Programming Language :: Python :: 3
    Operating System :: MacOS :: MacOS X
    Operating System :: POSIX :: Linux
platforms =
    Operating System :: MacOS :: MacOS X
    Operating System :: POSIX :: Linux

[options]
# We set packages to find: to automatically find all sub-packages
packages = find:
install_requires =
    flask
    pandas
    pytest
    sqlalchemy
    werkzeug
 
python_requires = >=3.9, <4
 
[options.packages.find]
exclude =
    tests
    tests.*
 
[options.extras_require]
dev =
    build
    coverage
    pylint
    pytest
    twine
test =
    coverage
    pylint
    pytest
build =
    build
    twine