services:
  sdtp_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8000:8000"
    container_name: sdtp_api
    command: poetry run python bin/run_sdtp_service.py
    healthcheck:
      test: curl http://localhost:8000 || exit 1
      interval: 5s
      retries: 10
      timeout: 300s

  request_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8002:8002"
    container_name: request_api
    command: poetry run python bin/run_request_service.py

  queue_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8001:8001"
    container_name: queue_api
    command: poetry run python bin/run_queue_service.py

  test:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: test
    container_name: test
    depends_on:
      sdtp_api:
        condition: service_healthy
    command: poetry run pytest -s tests/