services:
  sdtp_api:
    platform: linux/x86_64
    ports:
      - "8000:8000"
    container_name: sdtp_api
    image: docker-registry.pdmz.lasp.colorado.edu/datasystems/sdtp_api:latest
    volumes:
      - shared_data:/root/
      - /home/mabo8927/filesystem:/filesystem
      - /home/mabo8927/subscriber_queues:/subscriber_queues
      - /home/mabo8927/logs:/root/logs
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn sdtp_api:sdtp_app -b 0.0.0.0:8000 --log-level debug --threads 1 --max-requests 5 --timeout 120"

  queue_api:
    platform: linux/x86_64
    ports:
      - "8001:8001"
    container_name: sdtp_queue_api
    image: docker-registry.pdmz.lasp.colorado.edu/datasystems/sdtp_queue_api:latest
    volumes:
      - shared_data:/root/
      - /home/mabo8927/filesystem:/filesystem
      - /home/mabo8927/subscriber_queues:/subscriber_queues
      - /home/mabo8927/logs:/root/logs
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn queue_api:queue_app -b 0.0.0.0:8001 --log-level debug --threads 1 --max-requests 5 --timeout 120"

  request_api:
    platform: linux/x86_64
    ports:
      - "8002:8002"
    container_name: sdtp_request_api
    image: docker-registry.pdmz.lasp.colorado.edu/datasystems/sdtp_request_api:latest
    volumes:
      - shared_data:/root/
      - /home/mabo8927/filesystem:/filesystem
      - /home/mabo8927/subscriber_queues:/subscriber_queues
      - /home/mabo8927/logs:/root/logs
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn request_api:request_app -b 0.0.0.0:8002 --log-level debug --threads 1 --max-requests 5 --timeout 120"

volumes:
  shared_data: