services:
  sdtp_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    container_name: sdtp_api
    command: poetry run python bin/run_sdtp_servers.py
    healthcheck:
      test: curl http://localhost:8000 || exit 1
      interval: 5s
      retries: 10
      timeout: 300s