services:
  sdtp_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8000:8000"
    container_name: sdtp_api
    volumes:
      - shared_data:/root/
      - ~/filesystem:/filesystem
      - ~/subscriber_queues:/subscriber_queues
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn sdtp_api:sdtp_app -b 0.0.0.0:8000 --log-level debug --threads 4"

  queue_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8001:8001"
    container_name: sdtp_queue_api
    volumes:
      - shared_data:/root/
      - ~/filesystem:/filesystem
      - ~/subscriber_queues:/subscriber_queues
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn queue_api:queue_app -b 0.0.0.0:8001 --log-level debug --threads 4"

  request_api:
    platform: linux/x86_64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: base
    ports:
      - "8002:8002"
    container_name: sdtp_request_api
    volumes:
      - shared_data:/root/
      - ~/filesystem:/filesystem
      - ~/subscriber_queues:/subscriber_queues
    command: bash -c " \
      cd lasp_sdtp/server/ && \
      gunicorn request_api:request_app -b 0.0.0.0:8002 --log-level debug --threads 4"

volumes:
  shared_data: