CREATE TABLE Accounts
(
    username            VARCHAR2(30) NOT NULL,
    role                VARCHAR2(10) NOT NULL,
    registrationOpen    NUMBER(1)    NOT NULL,
    certUid             VARCHAR2(20),
    registrationDate    DATE,
    CONSTRAINT registration_open_constraint CHECK (registrationOpen IN (0, 1)),
    CONSTRAINT role_constraint CHECK (role IN ('admin', 'subscriber')),
    PRIMARY KEY (username)
);

CREATE TABLE Shortnames
(
    shortname       VARCHAR2(255) NOT NULL,
    filenamePattern VARCHAR2(255) NOT NULL,
    PRIMARY KEY (shortname)
);

CREATE TABLE Files
(
    fileid       NUMBER(15) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name         VARCHAR2(255) NOT NULL,
    checksum     VARCHAR2(71)  NOT NULL,
    "size"       FLOAT         NOT NULL,
    expires      DATE          NOT NULL,
    stream       VARCHAR2(255) NOT NULL,
    shortname    VARCHAR2(255) NOT NULL,
    version      VARCHAR2(5)   NOT NULL,
    ingestDate   DATE          NOT NULL,
    available    NUMBER(1)     NOT NULL,
    deletionDate DATE,
    CONSTRAINT fileid_constraint CHECK (fileid > 0),
    CONSTRAINT available_constraint CHECK (available IN (0, 1)),
    FOREIGN KEY (shortname) REFERENCES Shortnames (shortname),
    PRIMARY KEY (fileid)
);

CREATE TABLE TagsAndExtras
(
    fileid    NUMBER(15)    NOT NULL,
    fieldName VARCHAR2(255) NOT NULL,
    fieldType VARCHAR2(5)   NOT NULL,
    value     VARCHAR2(255) NOT NULL,
    CONSTRAINT field_type_constraint CHECK (fieldType IN ('tag', 'extra')),
    FOREIGN KEY (fileid) REFERENCES Files (fileid),
    PRIMARY KEY (fileid, fieldName, fieldType)
);

CREATE TABLE FileQueue
(
    username  VARCHAR2(30) NOT NULL,
    fileid    NUMBER(15)   NOT NULL,
    entryDate DATE         NOT NULL,
    expires   DATE         NOT NULL,
    FOREIGN KEY (fileid) REFERENCES Files (fileid),
    FOREIGN KEY (username) REFERENCES Accounts (username),
    PRIMARY KEY (username, fileid)
);

CREATE TABLE Missions
(
    mission         VARCHAR2(30)  NOT NULL,
    ingestDirectory VARCHAR2(255) NOT NULL,
    CONSTRAINT missions_uc UNIQUE (mission, ingestDirectory),
    PRIMARY KEY (mission)
);

CREATE TABLE MissionAccountMapping
(
    mission VARCHAR2(30) NOT NULL,
    account VARCHAR2(30) NOT NULL,
    FOREIGN KEY (mission) REFERENCES Missions (mission),
    FOREIGN KEY (account) REFERENCES Accounts (username),
    PRIMARY KEY (mission, account)
);

CREATE TABLE MissionShortnameMapping
(
    mission   VARCHAR2(30)  NOT NULL,
    shortname VARCHAR2(255) NOT NULL,
    FOREIGN KEY (mission) REFERENCES Missions (mission),
    FOREIGN KEY (shortname) REFERENCES Shortnames (shortname),
    PRIMARY KEY (mission, shortname)
);

CREATE TABLE Transactions
(
    transactionid  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    action         VARCHAR2(255) NOT NULL,
    username       VARCHAR2(30)  NOT NULL,
    startTime      DATE          NOT NULL,
    fileid         NUMBER(15),
    source         VARCHAR2(255),
    destination    VARCHAR2(255),
    endTime        DATE,
    responseStatus VARCHAR2(255),
    FOREIGN KEY (fileid) REFERENCES Files (fileid),
    FOREIGN KEY (username) REFERENCES Accounts (username),
    PRIMARY KEY (transactionid)
);

-- Add data for currently supported missions
INSERT INTO Accounts (username, role, registrationOpen, certUid, registrationDate) VALUES ('lasp_admin', 'admin', 0, 'admin_cert', TO_DATE('2022/11/08', 'YYYY/MM/DD'));
INSERT INTO Accounts (username, role, registrationOpen, certUid, registrationDate) VALUES ('ges_disc', 'subscriber', 1, 'test_cert', NULL);

INSERT INTO Missions (mission, ingestDirectory) VALUES ('TSIS2', '/path/to/tsis2/data/');

INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_L1', 'tsis2_L1_(?P<date>\d{8}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SIM_CAL', 'tsis2_sim_cal_v(?P<version>\d{2}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TIM_CAL', 'tsis2_tim_cal_v(?P<version>\d{2}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SIM_L2', 'tsis2_sim_L2_v(?P<version>\d{2})_(?P<date>\d{8}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TIM_L2', 'tsis2_tim_L2_v(?P<version>\d{2})_(?P<date>\d{8}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SC_L2', 'tsis2_sc_L2_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).zip');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SSI_L3_12HR_TXT', 'tsis2_ssi_L3_c12h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).txt');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SSI_L3_24HR_TXT', 'tsis2_ssi_L3_c24h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).txt');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TSI_L3_06HR_TXT', 'tsis2_tsi_L3_c06h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).txt');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TSI_L3_24HR_TXT', 'tsis2_tsi_L3_c24h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).txt');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SSI_L3_12HR_NC', 'tsis2_ssi_L3_c12h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).nc');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_SSI_L3_24HR_NC', 'tsis2_ssi_L3_c24h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).nc');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TSI_L3_06HR_NC', 'tsis2_tsi_L3_c06h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).nc');
INSERT INTO Shortnames (shortname, filenamePattern) VALUES ('TSIS2_TSI_L3_24HR_NC', 'tsis2_tsi_L3_c24h_v(?P<version>\d{2})_(?P<start_date>\d{8})_(?P<end_date>\d{8}).nc');

INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_L1');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SIM_CAL');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SIM_L2');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SSI_L3_12HR_NC');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SSI_L3_12HR_TXT');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SSI_L3_24HR_NC');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SSI_L3_24HR_TXT');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TIM_CAL');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TIM_L2');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_SC_L2');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TSI_L3_06HR_NC');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TSI_L3_06HR_TXT');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TSI_L3_24HR_NC');
INSERT INTO MissionShortnameMapping (Mission, Shortname) VALUES ('TSIS2', 'TSIS2_TSI_L3_24HR_TXT');
