CREATE TABLE accounts (
    username VARCHAR2(30) NOT NULL,
    role VARCHAR2(10) NOT NULL,
    allowed_data_products VARCHAR2(255),
    registration_open NUMBER(1) NOT NULL,
    certuid VARCHAR2(20),
    registration_date DATE,
    registration_expires DATE,
    CONSTRAINT registration_open_constraint CHECK (registration_open IN (0, 1)),
    CONSTRAINT role_constraint CHECK (role IN ('admin', 'subscriber')),
    CONSTRAINT accounts_uc UNIQUE(username, certuid),
    PRIMARY KEY(username)
);

CREATE TABLE available_files (
    fileid NUMBER(15) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR2(255) NOT NULL,
    checksum VARCHAR2(71) NOT NULL,
    data_product_id VARCHAR2(30) NOT NULL,
    "size" FLOAT NOT NULL,
    expires DATE NOT NULL,
    stream VARCHAR2(255) NOT NULL,
    shortname VARCHAR2(255) NOT NULL,
    version VARCHAR2(3) NOT NULL,
    "date" DATE NOT NULL,
    CONSTRAINT available_files_uc UNIQUE(name, checksum),
    PRIMARY KEY(fileid)
);

CREATE TABLE metadata (
    fileid NUMBER(15) NOT NULL,
    field_name VARCHAR2(255) NOT NULL,
    field_type VARCHAR2(5) NOT NULL,
    value VARCHAR2(255) NOT NULL,
    CONSTRAINT field_type CHECK (field_type IN ('tag', 'extra')),
    FOREIGN KEY(fileid) REFERENCES available_files(fileid),
    PRIMARY KEY (fileid, field_name, field_type)
);

CREATE TABLE file_queue (
    queueid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username VARCHAR2(30) NOT NULL,
    fileid NUMBER(15) NOT NULL,
    entry_date DATE NOT NULL,
    expires DATE NOT NULL,
    FOREIGN KEY(fileid) REFERENCES available_files(fileid),
    FOREIGN KEY(username) REFERENCES accounts(username),
    CONSTRAINT file_queue_uc UNIQUE(username, fileid),
    PRIMARY KEY(queueid)
);

CREATE TABLE transactions (
    transactionid NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    action VARCHAR2(255) NOT NULL,
    username VARCHAR2(30) NOT NULL,
    start_time DATE NOT NULL,
    fileid NUMBER(15),
    source VARCHAR2(255),
    destination VARCHAR2(255),
    end_time DATE,
    FOREIGN KEY(fileid) REFERENCES available_files(fileid),
    FOREIGN KEY(username) REFERENCES accounts(username),
    PRIMARY KEY(transactionid)
);