DROP SEQUENCE "FILE_METADATA_SEQ";
DROP TABLE "FILE_METADATA" PURGE;

DROP SEQUENCE "FILE_QUEUE_SEQ";
DROP TABLE "FILE_QUEUE" PURGE;

DROP SEQUENCE "TRANSACTIONS_SEQ";
DROP TABLE "TRANSACTIONS" PURGE;